train:
  image_dir: data/mesh2_train_images
  mask_dir:  data/mesh2_train_masks
  metadata_path: data/mesh2_train_metadata.json
  batch_size: 8
  learning_rate: 0.0001
  epochs: 15
  output_dir: checkpoints/mesh_stage2

inference:
  image_dir: data/mesh2_test_images
  mask_dir:  data/mesh2_test_masks
  metadata_path: data/mesh2_test_metadata.json
  model_path: checkpoints/mesh_stage2/mesh_stage2.pth
  output_dir: outputs/mesh_stage2
  batch_size: 4
  threshold: 0.3
